# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "hugo-theme-texify"
baseURL = "/"
defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
paginate = 10
summaryLength = 0

buildDrafts = false
buildFuture = false

# googleAnalytics = "G-XXXXXXXXX"
title = "David Suh の 일상."
toc=true
[author]
name = "David Suh"
image = "img/author.jpg"
headline = "A generally awesome human"
bio = "A little bit about me"
links = [
  { twitter = "https://twitter.com/username" }
]
[params.math]
enable = true # whether to enable math typesetting
use = "katex"  # katex or mathjax


customCSS = ['/css/custom.css']            # path to custom css files, relative to ./static
customJS = []      

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
identifier = "post" # section id
name = "Home"       # section display title
url = "/"           # path to the section
weight = 1          # order of sections
[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/post/"
weight = 2
[[menu.main]]
identifier = "about"
name = "About Me  "
url = "/about"
weight = 3
[[menu.main]]
identifier = "resume"
name = "CV/Resume"
url = "/resume"
weight = 4

[params]
description = "an example site for hugo theme TeXify" # website description
favicon = "favicon.ico" # path to website icon, relative to ./static
footnote = """
  Find me on <a class=link href=https://github.com/davidsuh11>GitHub</a> or <a class=link href=https://www.linkedin.com/in/david-suh12/>LinkedIn</a>.
"""

